language: python
python:
    - "3.7"

cache:
    pip: true

install:
    - pip install -r requirements.txt
    
script:
    - echo "python version $(python --version) running"
    - echo "pip version $(pip --version) running"
    - pytest tests/
    - mypy --no-strict-optional --ignore-missing-imports
